import { test, expect } from '@playwright/test';

function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}

test('Ask a question to Chatsy', async ({ page }) => {
  await page.goto('https://k12qauc.k12insight.com/static/k12insight_login.html');
  await page.goto('https://k12qauc.k12insight.com/static/k12insight_login.html');
  await page.getByPlaceholder('Username').fill('nsawant1+profile@zarca.com');
  await page.getByPlaceholder('Password').fill('Ninad@123');
  await page.getByRole('button', { name: 'LOG IN' }).click();
  await expect(page.getByRole('cell', { name: 'Customer', exact: true })).toBeVisible({timeout:30000});
  const loadingElement = page.locator('img[role="img"][alt="loading"]');
  //await loadingElement.waitFor({ state: 'visible' });
  await loadingElement.waitFor({ state: 'hidden' });
  await expect(page.getByText('Show All')).toBeVisible();
  const startTime = new Date().getTime();
  console.log("Timer started");
  await expect(page.getByText('Let’s Talk!')).toBeVisible({ timeout: 10000 });
  await page.getByRole('cell', { name: 'Let’s Talk!', exact: true }).getByRole('img').click();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Chatbot Logo').locator('img')).toBeVisible({ timeout: 15000 });
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByText('Ways to connect')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Chat', { exact: true })).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Email')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByText('Terms of Use and Privacy')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Close')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('What can I help you with')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('First, can you tell me how')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Employee')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Other')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByPlaceholder('Enter your message here')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').locator('#chatBodyWrapper div').filter({ hasText: 'Let’s Talk! Assistant byK12' }).first()).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByText('Let’s Talk! Assistant byK12')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').locator('label')).toContainText('Ways to connect');
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Chat', { exact: true })).toContainText('Chat');
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Email')).toContainText('Email');
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('What can I help you with')).toContainText('What can I help you with today?');
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('First, can you tell me how')).toContainText('First, can you tell me how you’re connected');
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Other')).toContainText('Other');
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Let’s Talk! Assistant')).toContainText('Let’s Talk! Assistant');
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('K12 Insight', { exact: true })).toContainText('K12 Insight');
  await page.frameLocator('iframe[title="Letstalk Assistant"]').getByPlaceholder('Enter your message here').click();
  await page.frameLocator('iframe[title="Letstalk Assistant"]').getByPlaceholder('Enter your message here').fill('Who are landing pages?');
  await page.frameLocator('iframe[title="Letstalk Assistant"]').locator('.k12lta-sendMessage').click();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Edited-custom error msg--')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Live chat with our team')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Submit as Email')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Ask a new Question')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Edited-custom error msg--')).toContainText('Edited-custom error msg--check for error msg on qauc server. check again ok .');
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Live chat with our team')).toContainText('Live chat with our team');
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Submit as Email')).toContainText('Submit as Email');
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Ask a new Question')).toContainText('Ask a new Question');
  await page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Close').click();
  const endTime = new Date().getTime();
  const elapsedTime = endTime - startTime;
    
    console.log("Timer ended");
    console.log("Elapsed time: " + elapsedTime + " milliseconds");
});

test('Submit internal form', async ({ page }) => {
  
  await page.goto('https://k12qauc.k12insight.com/static/k12insight_login.html');
  await page.getByPlaceholder('Username').fill('nsawant1+profile@zarca.com');
  await page.getByPlaceholder('Password').fill('Ninad@123');
  await page.getByRole('button', { name: 'LOG IN' }).click();
  await expect(page.getByRole('cell', { name: 'Customer', exact: true })).toBeVisible({timeout:30000});
  const loadingElement = page.locator('img[role="img"][alt="loading"]');
  await loadingElement.waitFor({ state: 'hidden' });
  await expect(page.getByText('Show All')).toBeVisible();
  const startTime = new Date().getTime();
  console.log("Timer started");
  await expect(page.getByText('Let’s Talk!')).toBeVisible({ timeout: 10000 });
  await page.getByTitle('Create Dialogue').click();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByText('Observation')).toBeVisible({ timeout: 10000 });
  await expect(page.frameLocator('#ifrmInternalDialouge').getByText('Phone Call')).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByText('In-Person')).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByText('Letter')).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByText('Other')).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByText('Social Media')).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByText('Origin*')).toBeVisible();
  await page.frameLocator('#ifrmInternalDialouge').getByLabel('Observation').check();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByText('Contact information')).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByText('Record the customer\'s name')).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByPlaceholder('Name')).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByPlaceholder('Email')).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByPlaceholder('Phone')).toBeVisible();
  await page.frameLocator('#ifrmInternalDialouge').getByPlaceholder('Name').click();
  await page.frameLocator('#ifrmInternalDialouge').getByPlaceholder('Name').fill('Ninad');
  await page.frameLocator('#ifrmInternalDialouge').getByPlaceholder('Name').press('Tab');
  await page.frameLocator('#ifrmInternalDialouge').getByPlaceholder('Email').fill('nsawant1@zarca.com');
  await page.frameLocator('#ifrmInternalDialouge').getByPlaceholder('Email').press('Tab');
  await page.frameLocator('#ifrmInternalDialouge').getByPlaceholder('Phone').fill('1324567980');
  await expect(page.frameLocator('#ifrmInternalDialouge').getByText('Received from *')).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').locator('div').filter({ hasText: /^Student$/ })).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').locator('div').filter({ hasText: /^Employee$/ })).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').locator('div').filter({ hasText: /^Parent\/Guardian$/ })).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').locator('div').filter({ hasText: /^Community Member$/ })).toBeVisible();
  await page.frameLocator('#ifrmInternalDialouge').locator('div').filter({ hasText: /^Employee$/ }).click();
  await expect(page.frameLocator('#ifrmInternalDialouge').locator('form')).toContainText('Student');
  await expect(page.frameLocator('#ifrmInternalDialouge').locator('form')).toContainText('Employee');
  await expect(page.frameLocator('#ifrmInternalDialouge').locator('form')).toContainText('Parent/Guardian');
  await expect(page.frameLocator('#ifrmInternalDialouge').locator('form')).toContainText('Community Member');
  await expect(page.frameLocator('#ifrmInternalDialouge').getByText('Assign to*')).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByText('Please provide one of the')).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByLabel('Number')).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByText('Topic')).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByText('Users')).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByLabel('user')).toBeVisible();
  await page.frameLocator('#ifrmInternalDialouge').getByLabel('Number').click();
  await page.frameLocator('#ifrmInternalDialouge').getByText('Automation Chatbot').click();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByLabel('user')).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByText('Type *')).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByText('QuestionCommentSuggestionConcernCompliment')).toBeVisible();
  await page.frameLocator('#ifrmInternalDialouge').locator('#Comment1').click();
  await page.frameLocator('#ifrmInternalDialouge').getByText('Comment Content').click();
  await page.frameLocator('#ifrmInternalDialouge').getByPlaceholder('Subject').click();
  await page.frameLocator('#ifrmInternalDialouge').getByPlaceholder('Subject').fill('Ninad subject');
  await page.frameLocator('#ifrmInternalDialouge').getByPlaceholder('Description').click();
  await page.frameLocator('#ifrmInternalDialouge').getByPlaceholder('Description').fill('Ninad Description');
  await expect(page.frameLocator('#ifrmInternalDialouge').getByText('Add Attachment')).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByText('Add Internal Comment')).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByText('Add me to Dialogue')).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByText('Send Customer Thank You email')).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByLabel('Select Categories')).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByLabel('Select Categories')).toBeVisible();
  await page.frameLocator('#ifrmInternalDialouge').getByLabel('Select Categories').click();
  await page.frameLocator('#ifrmInternalDialouge').getByText('Enrollment: Other').click();
  await page.frameLocator('#ifrmInternalDialouge').getByLabel('Select Categories').click();
  await page.frameLocator('#ifrmInternalDialouge').getByLabel('Select Categories').click();
  await page.frameLocator('#ifrmInternalDialouge').locator('form div').filter({ hasText: 'Enrollment: Other' }).nth(1).click();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByRole('option', { name: 'Enrollment: Other' })).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByText('Submit as Unopened')).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').locator('.mat-menu-trigger')).toBeVisible();
  await expect(page.frameLocator('#ifrmInternalDialouge').getByText('Required*')).toBeVisible();
  await page.frameLocator('#ifrmInternalDialouge').getByText('Submit as Unopened').click();
  await expect(page.getByText('Dialogue has been')).toBeVisible();
  const endTime = new Date().getTime();
  const elapsedTime = endTime - startTime;  
  console.log("Timer ended");
  console.log("Elapsed time: " + elapsedTime + " milliseconds");

});


test('Chat in Fab', async ({ page }) => {

  await page.goto('https://betaprofile.blogspot.com/2024/07/test-fab.html');
  await expect(page.getByLabel('ChatBot Icon')).toHaveScreenshot;
  await sleep(3000);
  const startTime = new Date().getTime();
  console.log("Timer started");
  await page.getByLabel('ChatBot Icon').click();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Chatbot Logo').locator('img')).toBeVisible();
  const endTime = new Date().getTime();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByText('Ways to connect')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Close')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Chat', { exact: true })).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Email')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByRole('link', { name: 'Terms of Use' })).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByRole('link', { name: 'Privacy Policy' })).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByText('Terms of Use and Privacy')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('What can I help you with')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('First, can you tell me how')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Parent/Guardian')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Employee')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Student')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Community Member')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Other')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByPlaceholder('Enter your message here')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Select Language')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByText('Let’s Talk! Assistant byK12')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Let’s Talk Assistant Icon')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Let’s Talk! Assistant')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('by')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('K12 Insight')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').locator('label')).toContainText('Ways to connect');
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Chat', { exact: true })).toContainText('Chat');
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Email')).toContainText('Email');
  await page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Community Member').click();
  await page.frameLocator('iframe[title="Letstalk Assistant"]').getByPlaceholder('Enter your message here').click();
  await page.frameLocator('iframe[title="Letstalk Assistant"]').getByPlaceholder('Enter your message here').fill('Who is the presid');
  await page.frameLocator('iframe[title="Letstalk Assistant"]').getByPlaceholder('Enter your message here').click();
  await page.frameLocator('iframe[title="Letstalk Assistant"]').getByPlaceholder('Enter your message here').fill('Who is the president of India?');
  await page.frameLocator('iframe[title="Letstalk Assistant"]').locator('.k12lta-sendMessage').click();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Sorry, I couldn\'t find an')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Live chat with our team')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Submit as Email')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Ask a new Question')).toBeVisible();
  await expect(page.frameLocator('iframe[title="Letstalk Assistant"]').getByLabel('Close')).toBeVisible();
  
  const elapsedTime = endTime - startTime;  
  console.log("Timer ended");
  console.log("Elapsed time: " + elapsedTime + " milliseconds");

})
